# flask-app/values.yaml
replicaCount: 1

image:
  repository: cometdiegoc/darenjacobsk8sflaskapp
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  name: my-app-service
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

nginx:
  service:
    type: LoadBalancer
  ingress:
    enabled: true
    hostname: example.local
