apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "flask-app.fullname" .) }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "flask-app.name" . }}
    release: {{ .Release.Name }}
