apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080  # Ensure this matches the container port
      protocol: TCP
      name: http
  selector:
    app: {{ include "flask-app.name" . }}
    release: {{ .Release.Name }}
